spring:
  application:
    name: findex

  datasource:
    ##url: jdbc:h2:mem:testdb   # 인메모리 DB
    url: jdbc:postgresql://crossover.proxy.rlwy.net:29817/railway
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${FINDEX_DB_PASSWORD}

#  h2:
#    console:
#      enabled: true
#      path: /h2-console       # http://localhost:8080/h2-console

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_updates: true
    defer-datasource-initialization: true

external:
  finance:
    base-url: "https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService"
    service-key: ${OPEN_API_SECRET}
