spring:
  application:
    name: findex

  datasource:
    url: jdbc:h2:mem:testdb   # 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console       # http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: update        # 개발/테스트용 (운영 X)
    show-sql: true

external:
  finance:
    base-url: "https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService"
    service-key: ${OPEN_API_SECRET}