spring:
  application:
    name: findex

  datasource:
    url: jdbc:h2:mem:testdb   # 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console       # http://localhost:8080/h2-console


  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

external:
  finance:
    base-url: "https://apis.data.go.kr/1160100/service/GetMarketIndexInfoService"
    service-key: ${OPEN_API_SECRET}